spring:
  cloud:
    gateway:
      routes:
      - id: catalogues_route
        uri: http://localhost:8010
        predicates:
        - Path=/catalogue
        - Weight=group1, 6
      - id: customers_route
        uri: http://localhost:8011
        predicates:
        - Path=/customers

#Actuator health check    
management:
  endpoints:
    web:
      exposure:
        include: "*"